name: CI/CD for Flask API

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете для развертывания

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t flask-app .  # Собираем Docker-образ из текущего каталога

      - name: Deploy to VPS (via SSH)
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Запускаем новый контейнер
            docker run -p 5000:5000 flask-app  # Убедитесь, что имя образа совпадает
          EOF
