name: CI/CD for Flask API

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете для развертывания

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Логин Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Пароль Docker Hub

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .  # Собираем Docker-образ из текущего каталога и тегируем его

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest  # Отправляем образ в Docker Hub

      - name: Deploy to VPS (via SSH)
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            # Загружаем образ из Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            # Останавливаем и удаляем старый контейнер, если он существует
            docker stop flask-app || true
            docker rm flask-app || true

            # Запускаем новый контейнер с образом из Docker Hub
            docker run -d --name flask-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          EOF
