name: CI/CD for Flask API

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете для развертывания

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/to/your/app  # Путь к вашему приложению на сервере
            git pull origin main  # Или другая команда для получения обновлений
            
            # Убедитесь, что виртуальное окружение существует, если нет, создайте его
            if [ ! -d "venv" ]; then
              python3 -m venv venv  # Создание виртуального окружения
            fi
            
            source venv/bin/activate  # Активация виртуального окружения
            
            pip install -r requirements.txt  # Установка зависимостей
            
            # Запуск вашего Flask приложения
            pkill python || true  # Убиваем старый процесс Python (если он запущен)
            nohup python script.py &  # Запускаем ваше приложение в фоновом режиме
          EOF
